# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
zh:
  languageCode: zh-Hans
  title: 万宏飞 | 简历
  params:
    description: 万宏飞的中文简历与项目经历
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/zh

# Uncomment the lines below to configure your website in a second language.
#en:
#  languageCode: en-us
#  contentDir: content/en
