# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: blue

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: '清华大学工程物理系'
    description: '万宏飞的中文简历，聚焦具身智能、自动驾驶仿真和实验探测数据分析。'
    twitter: ''
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: floating-theme-toggler

# Site footer
footer:
  copyright:
    notice: '© {year} 万宏飞. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: '2006年1月2日'
  time_format: '15:04'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false
